var $ = require('jquery')
var carousel = require('./js/com/carousel')
var gotop = require('./js/com/gotop')
var mod = require('./js/com/mod')
var tab = require('./js/com/tab')
var waterfall = require('./js/com/waterfall')
carousel.init($('.slide-box'))
gotop()
mod()
tab()
waterfall()
